name: dataquality
channels:
  - conda-forge
dependencies:
  - python=3.9.7
  - pandas~=1.3.3
  - scipy~=1.7.1
  - numpy~=1.21.3
  - scikit-learn~=1.0
  - pandasql
  # - modal
  - seaborn~=0.11.2
  - statsmodels
  - pymc3
  - tqdm~=4.62.3
  - click
  - rich
  # - optuna
  - matplotlib~=3.4.3
  # - adjusttext
  - pytorch==1.10.2
  - kmodes
  - ipykernel